/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CUTE_DESKTOP.glb --draco 
*/

import React from 'react'
import * as THREE from 'three'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

const MyPC = (props) => {
  const group = React.useRef()
  const { scene, animations } = useGLTF('models/CUTE_DESKTOP.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  let mixer = new THREE.AnimationMixer();




  useFrame((state, delta) => {

    let action = mixer.clipAction(animations[2], scene);
    action.play();
    mixer.update(delta);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RIGGING">
          <primitive object={nodes.Neck} />
        </group>
        <mesh name="PESCOÇO" geometry={nodes.PESCOÇO.geometry} material={materials.BRANCO} />
        <mesh name="BASE" geometry={nodes.BASE.geometry} material={materials.BRANCO} />
        <group name="GABINETE">
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.BRANCO} />
          <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.BRANCO} />
        </group>
        <mesh name="FRENTE" geometry={nodes.FRENTE.geometry} material={materials.CINZA} />
        <mesh name="PARAFUSO" geometry={nodes.PARAFUSO.geometry} material={materials['Material.004']} />
        <mesh name="FRENTE_DISK" geometry={nodes.FRENTE_DISK.geometry} material={materials.BRANCO} />
        <mesh name="DISK" geometry={nodes.DISK.geometry} material={materials['Material.002']} />
        <mesh name="CABO_MOUSE" geometry={nodes.CABO_MOUSE.geometry} material={materials.BRANCO} />
        <mesh name="BOTAO" geometry={nodes.BOTAO.geometry} material={materials.BRANCO} />
        <mesh name="MOUSE" geometry={nodes.MOUSE.geometry} material={materials.BRANCO} />
        <group name="MONITOR">
          <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={materials.CINZA} skeleton={nodes.Cube.skeleton} />
          <skinnedMesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.BRANCO} skeleton={nodes.Cube_1.skeleton} />
          <skinnedMesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials['Glass Simple']} skeleton={nodes.Cube_2.skeleton} />
          <skinnedMesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials['Material.003']} skeleton={nodes.Cube_3.skeleton} />
        </group>
        <skinnedMesh name="CAMERAS" geometry={nodes.CAMERAS.geometry} material={materials.CINZA} skeleton={nodes.CAMERAS.skeleton} />
        <skinnedMesh name="OLHOS" geometry={nodes.OLHOS.geometry} material={materials.OLHO} skeleton={nodes.OLHOS.skeleton} morphTargetDictionary={nodes.OLHOS.morphTargetDictionary} morphTargetInfluences={nodes.OLHOS.morphTargetInfluences} />
        <skinnedMesh name="OLHOS001" geometry={nodes.OLHOS001.geometry} material={materials.OLHO} skeleton={nodes.OLHOS001.skeleton} morphTargetDictionary={nodes.OLHOS001.morphTargetDictionary} morphTargetInfluences={nodes.OLHOS001.morphTargetInfluences} />
      </group>
    </group>
  )
}

useGLTF.preload('models/CUTE_DESKTOP.glb')

export default MyPC